begin;
do $$
declare customer uuid; staff uuid; admin uuid; product uuid; stock uuid; result jsonb; duplicate jsonb; v_order_id uuid; ticket uuid; pay_id text:=gen_random_uuid()::text; caught boolean; report jsonb; revenue_before numeric; expired_product uuid; expired_order uuid; fresh_order uuid; expired_stock uuid; ai_run uuid; before7 numeric; before30 numeric; boundary7 timestamptz; boundary30 timestamptz;
begin
 select id into admin from profiles where role='admin' limit 1;
 select id into customer from profiles where id<>admin order by created_at limit 1;
 select id into staff from profiles where id<>admin and id<>customer order by created_at limit 1;
 if customer is null or staff is null then raise exception 'test requires existing customer fixtures'; end if;
 update profiles set role='support' where id=staff;
 insert into discord_account_links(profile_id,discord_user_id,discord_username) values(customer,'999999999999999991','test-customer'),(staff,'999999999999999992','test-staff') on conflict(profile_id) do update set discord_user_id=excluded.discord_user_id;
 report:=discord_finance_report(admin,'total');revenue_before:=(report->>'revenue')::numeric;
 report:=discord_finance_report(admin,'7days');before7:=(report->>'revenue')::numeric;boundary7:=(report->>'range_start')::timestamptz;
 report:=discord_finance_report(admin,'30days');before30:=(report->>'revenue')::numeric;boundary30:=(report->>'range_start')::timestamptz;
 insert into products(name,slug,price,active,automatic_delivery) values('SQL fixture','fixture-'||gen_random_uuid(),10,true,true) returning id into product;
 caught:=false;
 begin perform discord_prepare_checkout('test-out-of-stock','999999999999999991','999999999999999990','999999999999999993',product); exception when others then if sqlerrm='OUT_OF_STOCK' then caught:=true;else raise;end if;end;
 if not caught then raise exception 'empty stock accepted'; end if;
 insert into supplier_stock_items(supplier_id,product_id,label,secret_content,status) values(admin,product,'fixture','DUMMY TEST DELIVERY','available') returning id into stock;
 result:=discord_prepare_checkout('test-checkout','999999999999999991','999999999999999990','999999999999999993',product);
 v_order_id:=(result->>'order_id')::uuid;
 if (result->>'amount_cents')::integer<>1000 then raise exception 'catalog price not used'; end if;
 duplicate:=discord_prepare_checkout('test-checkout','999999999999999991','999999999999999990','999999999999999993',product);
 if duplicate->>'order_id' is distinct from result->>'order_id' then raise exception 'duplicate checkout'; end if;
 if (select status from supplier_stock_items where id=stock)<>'reserved' then raise exception 'stock not reserved'; end if;
 if not exists(select from orders where id=v_order_id and user_id=customer and source='discord' and source_channel_id='999999999999999993') then raise exception 'origin or identity lost'; end if;
 insert into payments(order_id,provider,provider_payment_id,status,amount) values(v_order_id,'turbofypay',pay_id,'pending',10);
 caught:=false;
 begin perform discord_settle_payment(pay_id,jsonb_build_object('id',pay_id,'status','PAID','amountCents',999,'externalRef',v_order_id)); exception when others then if sqlerrm='PAYMENT_MISMATCH' then caught:=true;else raise;end if;end;
 if not caught then raise exception 'amount mismatch accepted'; end if;
 perform discord_settle_payment(pay_id,jsonb_build_object('id',pay_id,'status','PAID','amountCents',1000,'externalRef',v_order_id));
 perform discord_settle_payment(pay_id,jsonb_build_object('id',pay_id,'status','PAID','amountCents',1000,'externalRef',v_order_id));
 if (select count(*) from order_deliveries where order_deliveries.order_id=v_order_id)<>1 then raise exception 'duplicate automatic delivery'; end if;
 if (select status from orders where id=v_order_id)<>'delivered' then raise exception 'delivery not completed'; end if;
 perform discord_settle_payment(pay_id,jsonb_build_object('id',pay_id,'status','EXPIRED','amountCents',1000,'externalRef',v_order_id));
 if (select status from orders where id=v_order_id)<>'delivered' then raise exception 'paid order regressed'; end if;
 insert into discord_order_finance(order_id,cost,fee,note,updated_by) values(v_order_id,2,1,'SQL fixture',admin);
 report:=discord_finance_report(admin,'total');if (report->>'revenue')::numeric<>revenue_before+10 then raise exception 'finance omitted paid order';end if;
 caught:=false;begin perform discord_finance_report(customer,'total');exception when others then if sqlerrm='FORBIDDEN' then caught:=true;else raise;end if;end;if not caught then raise exception 'customer finance access';end if;
 report:=discord_finance_report(admin,'7days');if (report->>'revenue')::numeric<>before7+10 then raise exception '7-day report omitted paid fixture';end if;
 update orders set created_at=boundary7-interval '1 second' where id=v_order_id;
 report:=discord_finance_report(admin,'7days');if (report->>'revenue')::numeric<>before7 then raise exception '7-day boundary leaked fixture';end if;
 report:=discord_finance_report(admin,'30days');if (report->>'revenue')::numeric<>before30+10 then raise exception '30-day report omitted fixture';end if;
 update orders set created_at=boundary30-interval '1 second' where id=v_order_id;
 report:=discord_finance_report(admin,'30days');if (report->>'revenue')::numeric<>before30 then raise exception '30-day boundary leaked fixture';end if;
 update orders set created_at=now() where id=v_order_id;
 result:=discord_ticket_action('999999999999999991','999999999999999990','open',null,jsonb_build_object('reason','SQL test question','interaction_id','test-ticket','order_id',v_order_id));
 ticket:=(result->>'ticket_id')::uuid;
 caught:=false;
 begin perform discord_ticket_action('999999999999999991','999999999999999990','claim',ticket);exception when others then if sqlerrm='FORBIDDEN' then caught:=true;else raise;end if;end;
 if not caught then raise exception 'customer staff escalation'; end if;
 perform discord_ticket_action('999999999999999992','999999999999999990','claim',ticket);
 perform discord_ticket_action('999999999999999992','999999999999999990','close',ticket,'{"reason":"Duplicated request","outcome":"duplicate"}');
 if exists(select from support_tickets where id=ticket and (status='resolved' or resolved_by is not null)) then raise exception 'duplicate ticket counts for payroll'; end if;
 perform discord_ticket_action('999999999999999991','999999999999999990','rate',ticket,'{"stars":5,"comment":"Fixture"}');
 if not exists(select from discord_ticket_ratings where ticket_id=ticket and profile_id=customer) then raise exception 'rating not saved'; end if;
 insert into products(name,slug,price,active,automatic_delivery) values('Reservation fixture','fixture-'||gen_random_uuid(),10,true,true) returning id into expired_product;
 insert into supplier_stock_items(supplier_id,product_id,label,secret_content,status) values(admin,expired_product,'fixture','SECOND DUMMY TEST DELIVERY','available') returning id into expired_stock;
 result:=discord_prepare_checkout('test-expired-checkout','999999999999999991','999999999999999990','999999999999999993',expired_product);expired_order:=(result->>'order_id')::uuid;
 insert into payments(order_id,provider,provider_payment_id,status,amount) values(expired_order,'turbofypay','expiry-'||pay_id,'pending',10);
 perform discord_settle_payment('expiry-'||pay_id,jsonb_build_object('id','expiry-'||pay_id,'status','EXPIRED','amountCents',1000));
 result:=discord_prepare_checkout('test-restock-checkout','999999999999999991','999999999999999990','999999999999999993',expired_product);fresh_order:=(result->>'order_id')::uuid;
 insert into payments(order_id,provider,provider_payment_id,status,amount) values(fresh_order,'turbofypay','fresh-'||pay_id,'pending',10);
 perform discord_settle_payment('fresh-'||pay_id,jsonb_build_object('id','fresh-'||pay_id,'status','PAID','amountCents',1000));
 if (select status from discord_stock_reservations where stock_item_id=expired_stock and order_id=expired_order)<>'released' or (select status from discord_stock_reservations where stock_item_id=expired_stock and order_id=fresh_order)<>'used' then raise exception 'reservation history corrupt after resale';end if;
 result:=discord_ticket_action('999999999999999991','999999999999999990','open',null,'{"reason":"AI fixture question","interaction_id":"test-ai-ticket"}');ticket:=(result->>'ticket_id')::uuid;
 insert into discord_ai_settings(guild_id,enabled,mode,hourly_limit) values('999999999999999990',true,'automatic',1);
 result:=discord_reserve_ai('999999999999999991','999999999999999990',ticket,'reply');ai_run:=(result->>'run_id')::uuid;
 perform discord_ticket_action('999999999999999992','999999999999999990','claim',ticket);
 if discord_complete_ai(ai_run,'DUMMY AI RESPONSE',10) then raise exception 'AI replied after staff claimed';end if;
 if exists(select from support_messages where ticket_id=ticket and sender_role='ai') then raise exception 'paused AI message saved';end if;
 caught:=false;begin perform discord_reserve_ai('999999999999999991','999999999999999990',ticket,'reply');exception when others then if sqlerrm='AI_PAUSED' then caught:=true;else raise;end if;end;if not caught then raise exception 'AI did not pause';end if;
 if has_function_privilege('authenticated','discord_prepare_checkout(text,text,text,text,uuid,uuid,uuid,text)','EXECUTE') or has_function_privilege('anon','discord_settle_payment(text,jsonb)','EXECUTE') or has_function_privilege('authenticated','discord_ticket_action(text,text,text,uuid,jsonb)','EXECUTE') then raise exception 'backend RPC public'; end if;
end $$;
select 'PASS: real database stock lock, identity/origin, checkout replay, amount mismatch, atomic delivery, paid monotonicity, staff permissions, resolved-only payroll, ratings and grants; rolled back' as test_result;
rollback;
