import {useEffect,useState} from 'react';import{LogOut,Plus,Trash2,Package,ArrowLeft}from'lucide-react';import{supabase}from'./lib/supabase';
type Cat={id:string;name:string};type P={id:string;name:string;price:number;active:boolean;categories?:{name:string}|null};
export default function Admin(){
 const client=supabase!;
 const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[user,setUser]=useState<any>(null);const[role,setRole]=useState('');const[cats,setCats]=useState<Cat[]>([]);const[items,setItems]=useState<P[]>([]);const[msg,setMsg]=useState('');const[form,setForm]=useState({name:'',price:'',category_id:'',description:'',image_url:'',automatic_delivery:true});
 const load=async()=>{if(!client)return;const{data:{user}}=await client.auth.getUser();setUser(user);if(!user)return;const{data:p}=await client.from('profiles').select('role').eq('id',user.id).single();setRole(p?.role||'customer');if(p?.role==='admin'){const[{data:c},{data:i}]=await Promise.all([client.from('categories').select('id,name').order('name'),client.from('products').select('id,name,price,active,categories(name)').order('created_at',{ascending:false})]);setCats((c||[]) as Cat[]);setItems((i||[]) as unknown as P[])}};
 useEffect(()=>{load()},[]);
 const login=async(e:any)=>{e.preventDefault();if(!client)return;setMsg('');const{error}=await client.auth.signInWithPassword({email,password});if(error)setMsg(error.message);else load()};
 const add=async(e:any)=>{e.preventDefault();if(!client)return;const slug=form.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now();const{error}=await client.from('products').insert({name:form.name,slug,price:Number(form.price),category_id:form.category_id||null,description:form.description,image_url:form.image_url||null,automatic_delivery:form.automatic_delivery,active:true});if(error)setMsg(error.message);else{setForm({name:'',price:'',category_id:'',description:'',image_url:'',automatic_delivery:true});setMsg('Produto cadastrado!');load()}};
 const remove=async(id:string)=>{if(!supabase||!confirm('Excluir este produto?'))return;await client.from('products').delete().eq('id',id);load()};
 if(!client)return <div className="adminShell"><p>Supabase não configurado.</p></div>;
 if(!user)return <div className="adminShell"><a href="/" className="back"><ArrowLeft/> Voltar à loja</a><form className="adminLogin" onSubmit={login}><div className="adminLogo">N</div><h1>Painel Nexium</h1><p>Entre com sua conta administrativa.</p><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)} required/><button>Entrar</button>{msg&&<span className="adminMsg">{msg}</span>}</form></div>;
 if(role!=='admin')return <div className="adminShell"><div className="adminLogin"><h2>Acesso restrito</h2><p>Esta conta ainda não é administradora.</p><button onClick={()=>client.auth.signOut().then(()=>location.reload())}>Sair</button></div></div>;
 return <div className="adminShell"><div className="adminTop"><div><small>NEXIUM STORE</small><h1>Painel administrativo</h1></div><div><a href="/"><ArrowLeft/> Loja</a><button onClick={()=>client.auth.signOut().then(()=>location.reload())}><LogOut/> Sair</button></div></div><div className="adminGrid"><form className="productForm" onSubmit={add}><h2><Plus/> Novo produto</h2><label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Preço (R$)<input type="number" step="0.01" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/></label><label>Categoria<select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Sem categoria</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>URL da imagem<input placeholder="https://..." value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></label><label>Descrição<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.automatic_delivery} onChange={e=>setForm({...form,automatic_delivery:e.target.checked})}/> Entrega digital automática</label><button className="adminPrimary">Cadastrar produto</button>{msg&&<span className="adminMsg">{msg}</span>}</form><section className="adminProducts"><h2><Package/> Produtos</h2>{items.length===0?<p>Nenhum produto cadastrado.</p>:items.map(p=><div className="adminProduct" key={p.id}><div><b>{p.name}</b><span>{p.categories?.name||'Sem categoria'} • R$ {Number(p.price).toFixed(2).replace('.',',')}</span></div><button onClick={()=>remove(p.id)} aria-label="Excluir"><Trash2/></button></div>)}</section></div></div>
}