import{useEffect,useMemo,useState}from'react';import{Boxes,PackageCheck,Wallet,LogOut,Plus,Send,KeyRound,RefreshCw,LayoutDashboard,ShoppingCart,Landmark,History,AlertTriangle,CheckCircle2,Clock,Menu,X}from'lucide-react';import{supabase}from'./lib/supabase';
const money=(v:number)=>'R$ '+Number(v||0).toFixed(2).replace('.',',');
const dt=(v:string)=>new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});
export default function SupplierPanel(){
 const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[user,setUser]=useState<any>(null);const[profile,setProfile]=useState<any>(null);const[assignments,setAssignments]=useState<any[]>([]);const[orders,setOrders]=useState<any[]>([]);const[stock,setStock]=useState<any[]>([]);const[finance,setFinance]=useState<any>({total_earned:0,paid_total:0,pending_withdrawals:0,available_balance:0,earned_month:0,deliveries_month:0});const[withdrawals,setWithdrawals]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const[delivery,setDelivery]=useState('');const[file,setFile]=useState<File|null>(null);const[stockProduct,setStockProduct]=useState('');const[stockLabel,setStockLabel]=useState('');const[stockSecret,setStockSecret]=useState('');const[withdrawAmount,setWithdrawAmount]=useState('');const[msg,setMsg]=useState('');const[loading,setLoading]=useState(true);const[tab,setTab]=useState('dashboard');const[menu,setMenu]=useState(false);const[orderFilter,setOrderFilter]=useState('pending');
 const allowed=profile&&['supplier','admin'].includes(profile.role);
 const fetchData=async(uid:string)=>{if(!supabase)return;const[{data:a},{data:o},{data:s},{data:f},{data:w}]=await Promise.all([supabase.from('supplier_products').select('supplier_id,product_id,cost_price,active,products(id,name,image_url)').eq('supplier_id',uid),supabase.rpc('supplier_order_feed'),supabase.from('supplier_stock_items').select('id,product_id,label,status,created_at').eq('supplier_id',uid).order('created_at',{ascending:false}),supabase.rpc('supplier_finance_summary'),supabase.from('supplier_withdrawals').select('*').eq('supplier_id',uid).order('requested_at',{ascending:false})]);setAssignments(a||[]);setOrders(o||[]);setStock(s||[]);setFinance(f?.[0]||{total_earned:0,paid_total:0,pending_withdrawals:0,available_balance:0,earned_month:0,deliveries_month:0});setWithdrawals(w||[])};
 const load=async()=>{if(user)await fetchData(user.id)};
 const boot=async()=>{if(!supabase){setLoading(false);return}const{data:{user:u}}=await supabase.auth.getUser();setUser(u);if(!u){setLoading(false);return}const{data:p}=await supabase.from('profiles').select('id,full_name,role').eq('id',u.id).single();setProfile(p);if(p&&['supplier','admin'].includes(p.role))await fetchData(u.id);setLoading(false)};
 useEffect(()=>{boot()},[]);
 useEffect(()=>{if(!user||!allowed)return;const t=setInterval(()=>fetchData(user.id),20000);return()=>clearInterval(t)},[user?.id,profile?.role]);
 const login=async(e:any)=>{e.preventDefault();if(!supabase)return;setMsg('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error){setMsg('E-mail ou senha incorretos.');return}setLoading(true);await boot()};
 const addStock=async()=>{if(!supabase||!user||!stockProduct||!stockSecret.trim())return;const{error}=await supabase.from('supplier_stock_items').insert({supplier_id:user.id,product_id:stockProduct,label:stockLabel.trim()||null,secret_content:stockSecret.trim()});setMsg(error?error.message:'Item adicionado ao estoque.');if(!error){setStockLabel('');setStockSecret('');await load()}};
 const deliver=async()=>{if(!supabase||!user||!selected||(!delivery.trim()&&!file))return;setMsg('');let path=null;if(file){if(file.size>10*1024*1024){setMsg('Arquivo deve ter no máximo 10 MB.');return}const ext=(file.name.split('.').pop()||'bin').toLowerCase();path=user.id+'/supplier-deliveries/'+selected.order_id+'/'+Date.now()+'-'+Math.random().toString(36).slice(2)+'.'+ext;const{error}=await supabase.storage.from('support-files').upload(path,file);if(error){setMsg(error.message);return}}const{error}=await supabase.rpc('supplier_deliver_item',{p_order_item_id:selected.order_item_id,p_delivery_text:delivery.trim(),p_attachment_path:path,p_attachment_name:file?.name||null});setMsg(error?error.message:'Produto entregue e valor lançado no financeiro.');if(!error){setSelected(null);setDelivery('');setFile(null);await load()}};
 const requestWithdrawal=async()=>{if(!supabase)return;const amount=Number(withdrawAmount.replace(',','.'));if(!amount||amount<=0){setMsg('Digite um valor válido.');return}const{error}=await supabase.rpc('supplier_request_withdrawal',{p_amount:amount});setMsg(error?(error.message.includes('insufficient')?'Saldo disponível insuficiente.':error.message):'Solicitação enviada para a Nexium.');if(!error){setWithdrawAmount('');await load()}};
 const pending=orders.filter(x=>!x.delivered).length,delivered=orders.filter(x=>x.delivered).length,available=stock.filter(x=>x.status==='available').length,lowProducts=assignments.filter(a=>stock.filter(s=>s.product_id===a.product_id&&s.status==='available').length<=3);
 const filteredOrders=useMemo(()=>orders.filter(o=>orderFilter==='all'||(orderFilter==='pending'?!o.delivered:o.delivered)),[orders,orderFilter]);
 const nav=[['dashboard','Visão geral',LayoutDashboard],['orders','Pedidos',ShoppingCart],['stock','Estoque',KeyRound],['finance','Financeiro',Wallet],['withdraw','Saques',Landmark]];
 if(loading)return <main className="supplierPage"><div className="supplierCenter">Carregando...</div></main>;
 if(!user)return <main className="supplierPage"><form className="supplierLogin" onSubmit={login}><div className="supplierLogo"><Boxes/></div><small>NEXIUM STORE</small><h1>Painel do Fornecedor</h1><p>Gerencie produtos, entregas e financeiro.</p><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)} required/><button>Entrar</button>{msg&&<span>{msg}</span>}</form></main>;
 if(!allowed)return <main className="supplierPage"><div className="supplierCenter"><Boxes/><h2>Conta sem acesso de fornecedor</h2><p>Peça ao administrador da Nexium para liberar seu painel.</p><button onClick={async()=>{await supabase?.auth.signOut();location.reload()}}>Sair</button></div></main>;
 return <main className="supplierPage supplierV2"><header className="supplierHeader"><div><button className="supplierMenuBtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="supplierLogo small"><Boxes/></div><span><small>NEXIUM STORE</small><b>Portal do Fornecedor</b></span></div><div className="supplierIdentity"><span><b>{profile.full_name||'Fornecedor'}</b><small>Fornecedor</small></span><button onClick={async()=>{await supabase?.auth.signOut();location.reload()}}><LogOut/></button></div></header><nav className={'supplierNav '+(menu?'open':'')}>{nav.map(([id,label,Icon]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setMenu(false)}}><Icon/>{label}{id==='orders'&&pending>0?<i>{pending}</i>:null}</button>)}</nav>
 <div className="supplierContent">{msg&&<div className="supplierToast" onClick={()=>setMsg('')}>{msg}<button>×</button></div>}
 {tab==='dashboard'&&<><div className="supplierWelcome"><div><small>VISÃO GERAL</small><h1>Olá, {profile.full_name?.split(' ')[0]||'Fornecedor'}.</h1><p>Acompanhe suas entregas, estoque e saldo Nexium em tempo real.</p></div><button onClick={load}><RefreshCw/> Atualizar</button></div><section className="supplierStats"><div><Clock/><span><small>Aguardando entrega</small><b>{pending}</b></span></div><div><PackageCheck/><span><small>Entregues</small><b>{delivered}</b></span></div><div><KeyRound/><span><small>Estoque disponível</small><b>{available}</b></span></div><div><Wallet/><span><small>Saldo disponível</small><b>{money(finance.available_balance)}</b></span></div></section>{lowProducts.length>0&&<div className="supplierAlert"><AlertTriangle/><div><b>Atenção ao estoque</b><span>{lowProducts.map(a=>a.products?.name).join(', ')} {lowProducts.length===1?'está':'estão'} com 3 unidades ou menos.</span></div><button onClick={()=>setTab('stock')}>Repor estoque</button></div>}<section className="supplierDashGrid"><div className="supplierPanel"><div className="supplierPanelHead"><div><small>PRÓXIMAS ENTREGAS</small><h2>Pedidos aguardando você</h2></div><button onClick={()=>setTab('orders')}>Ver todos</button></div>{orders.filter(o=>!o.delivered).slice(0,5).map(o=><OrderCard key={o.order_item_id} o={o} onDeliver={()=>setSelected(o)}/>) }{!pending&&<p className="supplierEmpty">Tudo certo. Nenhuma entrega pendente.</p>}</div><div className="supplierPanel supplierFinanceMini"><div className="supplierPanelHead"><div><small>FINANCEIRO</small><h2>Resumo do mês</h2></div></div><div><span><small>Gerado este mês</small><b>{money(finance.earned_month)}</b></span><span><small>Entregas no mês</small><b>{finance.deliveries_month}</b></span><span><small>Aguardando saque</small><b>{money(finance.available_balance)}</b></span></div><button onClick={()=>setTab('withdraw')}>Solicitar pagamento</button></div></section></>}
 {tab==='orders'&&<section className="supplierPanel supplierFull"><div className="supplierPanelHead supplierOrdersHead"><div><small>PEDIDOS</small><h2>Central de entregas</h2></div><div className="supplierFilters"><button className={orderFilter==='pending'?'active':''} onClick={()=>setOrderFilter('pending')}>Pendentes {pending}</button><button className={orderFilter==='delivered'?'active':''} onClick={()=>setOrderFilter('delivered')}>Entregues {delivered}</button><button className={orderFilter==='all'?'active':''} onClick={()=>setOrderFilter('all')}>Todos</button></div></div>{filteredOrders.map(o=><OrderCard key={o.order_item_id} o={o} onDeliver={()=>setSelected(o)}/>)}{!filteredOrders.length&&<p className="supplierEmpty">Nenhum pedido nesta categoria.</p>}</section>}
 {tab==='stock'&&<section className="supplierStockGrid"><div className="supplierPanel"><div className="supplierPanelHead"><div><small>CATÁLOGO</small><h2>Estoque por produto</h2></div></div>{assignments.map(a=>{const av=stock.filter(s=>s.product_id===a.product_id&&s.status==='available').length;return <div className={'supplierProduct '+(av<=3?'low':'')} key={a.product_id}><span><b>{a.products?.name}</b><small>Custo Nexium: {money(a.cost_price)}</small></span><strong>{av} disponível{av!==1?'is':''}</strong></div>})}{!assignments.length&&<p className="supplierEmpty">Nenhum produto vinculado.</p>}</div><div className="supplierPanel supplierStockForm"><div className="supplierPanelHead"><div><small>REPOSIÇÃO</small><h2>Adicionar key / conta</h2></div></div><select value={stockProduct} onChange={e=>setStockProduct(e.target.value)}><option value="">Selecione o produto</option>{assignments.map(a=><option key={a.product_id} value={a.product_id}>{a.products?.name}</option>)}</select><input value={stockLabel} onChange={e=>setStockLabel(e.target.value)} placeholder="Identificação (opcional)"/><textarea rows={5} value={stockSecret} onChange={e=>setStockSecret(e.target.value)} placeholder="Key, login/senha, link ou dados do produto"/><button onClick={addStock}><Plus/> Adicionar ao estoque</button><small>Os dados secretos não são exibidos na listagem pública do painel.</small></div></section>}
 {tab==='finance'&&<><section className="supplierFinanceCards"><div><small>Total gerado</small><b>{money(finance.total_earned)}</b><span>Entregas registradas</span></div><div><small>Já pago</small><b>{money(finance.paid_total)}</b><span>Pagamentos confirmados</span></div><div><small>Em solicitação</small><b>{money(finance.pending_withdrawals)}</b><span>Aguardando administrador</span></div><div className="highlight"><small>Disponível</small><b>{money(finance.available_balance)}</b><span>Livre para solicitar</span></div></section><section className="supplierPanel supplierFull"><div className="supplierPanelHead"><div><small>EXTRATO</small><h2>Entregas e ganhos</h2></div></div>{orders.filter(o=>o.delivered).map(o=><div className="supplierStatement" key={o.order_item_id}><CheckCircle2/><span><b>{o.product_name}</b><small>Pedido #{o.order_id.slice(0,8)} • {dt(o.ordered_at)}</small></span><strong>+ {money(Number(o.cost_price)*Number(o.quantity))}</strong></div>)}{!delivered&&<p className="supplierEmpty">Seu extrato aparecerá após as primeiras entregas.</p>}</section></>}
 {tab==='withdraw'&&<section className="supplierWithdrawGrid"><div className="supplierPanel supplierWithdrawBox"><small>SEU SALDO</small><h2>{money(finance.available_balance)}</h2><p>Solicite o valor disponível. A Nexium analisa e registra o pagamento pelo painel administrativo.</p><label>Valor da solicitação<div><span>R$</span><input inputMode="decimal" placeholder="0,00" value={withdrawAmount} onChange={e=>setWithdrawAmount(e.target.value)}/></div></label><button disabled={Number(finance.available_balance)<=0} onClick={requestWithdrawal}><Landmark/> Solicitar pagamento</button></div><div className="supplierPanel"><div className="supplierPanelHead"><div><small>HISTÓRICO</small><h2>Solicitações</h2></div></div>{withdrawals.map(w=><div className="supplierWithdrawalRow" key={w.id}><History/><span><b>{money(w.amount)}</b><small>{dt(w.requested_at)}</small></span><strong className={w.status}>{w.status==='pending'?'Pendente':w.status==='paid'?'Pago':'Recusado'}</strong></div>)}{!withdrawals.length&&<p className="supplierEmpty">Nenhuma solicitação realizada.</p>}</div></section>}
 </div>{selected&&<div className="supplierModal"><div><button className="supplierClose" onClick={()=>setSelected(null)}>×</button><small>ENTREGA DIGITAL</small><h2>{selected.product_name}</h2><p>Pedido #{selected.order_id.slice(0,8)}. Ao entregar, {money(Number(selected.cost_price)*Number(selected.quantity))} será lançado no seu financeiro.</p><textarea rows={5} value={delivery} onChange={e=>setDelivery(e.target.value)} placeholder="Login, senha, key, link ou instruções..."/><label>Anexar print/PDF<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{file&&<span>{file.name}</span>}<button className="supplierDeliver" onClick={deliver}><Send/> Confirmar entrega</button></div></div>}</main>
}
function OrderCard({o,onDeliver}:{o:any,onDeliver:()=>void}){return <article className="supplierOrder"><div><span className={'supplierOrderStatus '+(o.delivered?'done':'waiting')}>{o.delivered?'ENTREGUE':'AGUARDANDO'}</span><b>{o.product_name}</b><small>{o.variant_name||'Produto digital'} • Qtd. {o.quantity}</small><small>Pedido #{o.order_id.slice(0,8)} • {dt(o.ordered_at)}</small></div><div><strong>{money(Number(o.cost_price)*Number(o.quantity))}</strong>{o.delivered?<span className="supplierDone"><CheckCircle2/> Concluído</span>:<button onClick={onDeliver}><Send/> Enviar produto</button>}</div></article>}
