import{useEffect,useState}from'react';import{Headphones,LogOut,Send,RefreshCw,Inbox,Clock3,CheckCircle2}from'lucide-react';import{supabase}from'./lib/supabase';

export default function SupportPanel(){
 const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[user,setUser]=useState<any>(null);const[profile,setProfile]=useState<any>(null);const[tickets,setTickets]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const[messages,setMessages]=useState<any[]>([]);const[reply,setReply]=useState('');const[msg,setMsg]=useState('');const[loading,setLoading]=useState(true);
 const allowed=profile&&['support','admin'].includes(profile.role);
 const loadTickets=async()=>{if(!supabase)return;const{data}=await supabase.from('support_tickets').select('*').order('updated_at',{ascending:false}).limit(100);setTickets(data||[])};
 const loadMessages=async(id:string)=>{if(!supabase)return;const{data}=await supabase.from('support_messages').select('*').eq('ticket_id',id).order('created_at');setMessages(data||[])};
 const boot=async()=>{if(!supabase){setLoading(false);return}const{data:{user:u}}=await supabase.auth.getUser();setUser(u);if(!u){setLoading(false);return}const{data:p}=await supabase.from('profiles').select('id,full_name,role').eq('id',u.id).single();setProfile(p);if(p&&['support','admin'].includes(p.role))await loadTickets();setLoading(false)};
 useEffect(()=>{boot()},[]);
 useEffect(()=>{if(!allowed)return;const id=setInterval(async()=>{await loadTickets();if(selected)await loadMessages(selected.id)},4000);return()=>clearInterval(id)},[allowed,selected?.id]);
 const login=async(e:any)=>{e.preventDefault();if(!supabase)return;setMsg('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error){setMsg('E-mail ou senha incorretos.');return}setLoading(true);await boot()};
 const open=async(t:any)=>{setSelected(t);await loadMessages(t.id)};
 const send=async()=>{if(!supabase||!user||!selected||!reply.trim())return;const name=profile?.full_name||'Equipe Nexium';const staffRole=profile?.role==='admin'?'Dono':'Suporte';const{data,error}=await supabase.from('support_messages').insert({ticket_id:selected.id,sender_id:user.id,sender_name:name,sender_role:staffRole,message:reply.trim()}).select('*').single();if(error){setMsg(error.message);return}setMessages(x=>[...x,data]);setReply('');await supabase.from('support_tickets').update({status:'in_progress',updated_at:new Date().toISOString()}).eq('id',selected.id);setSelected({...selected,status:'in_progress'});await loadTickets()};
 const status=async(v:string)=>{if(!supabase||!selected)return;await supabase.from('support_tickets').update({status:v,updated_at:new Date().toISOString()}).eq('id',selected.id);setSelected({...selected,status:v});await loadTickets()};
 if(loading)return <main className="staffPage"><div className="staffLoading">Carregando painel...</div></main>;
 if(!user)return <main className="staffPage"><form className="staffLogin" onSubmit={login}><div className="staffMark"><Headphones/></div><small>NEXIUM STORE</small><h1>Painel de Suporte</h1><p>Acesso exclusivo para a equipe de atendimento.</p><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button>Entrar no painel</button>{msg&&<span>{msg}</span>}</form></main>;
 if(!allowed)return <main className="staffPage"><div className="staffDenied"><Headphones/><h2>Conta sem acesso ao suporte</h2><p>Peça ao administrador da Nexium para liberar o cargo de Suporte para esta conta.</p><button onClick={async()=>{await supabase?.auth.signOut();location.reload()}}>Sair</button></div></main>;
 const openCount=tickets.filter(t=>t.status==='open').length,inProgress=tickets.filter(t=>t.status==='in_progress').length,resolved=tickets.filter(t=>t.status==='resolved').length;
 return <main className="staffPage"><header className="staffHeader"><div><div className="staffMark small"><Headphones/></div><span><small>NEXIUM STORE</small><b>Central de Atendimento</b></span></div><div className="staffIdentity"><span><b>{profile.full_name||'Equipe Nexium'}</b><small>{profile.role==='admin'?'Dono':'Suporte'}</small></span><button onClick={async()=>{await supabase?.auth.signOut();location.reload()}}><LogOut/></button></div></header><section className="staffStats"><div><Inbox/><span><small>Novos</small><b>{openCount}</b></span></div><div><Clock3/><span><small>Em atendimento</small><b>{inProgress}</b></span></div><div><CheckCircle2/><span><small>Resolvidos</small><b>{resolved}</b></span></div></section><section className="staffWorkspace"><aside className={selected?'staffTickets hiddenMobile':''}><div className="staffListHead"><div><small>ATENDIMENTOS</small><h2>Tickets</h2></div><button onClick={loadTickets}><RefreshCw/></button></div>{tickets.length===0?<div className="staffEmpty">Nenhum ticket encontrado.</div>:tickets.map(t=><button key={t.id} className={'staffTicket '+(selected?.id===t.id?'active':'')} onClick={()=>open(t)}><div><b>{t.subject}</b><small>#{t.id.slice(0,8)} • {new Date(t.updated_at).toLocaleString('pt-BR')}</small></div><span className={'ticketStatus '+t.status}>{t.status==='open'?'Novo':t.status==='in_progress'?'Atendendo':'Resolvido'}</span></button>)}</aside><article className={'staffConversation '+(!selected?'empty':'')}>{!selected?<div className="staffEmptyConversation"><Headphones/><h2>Selecione um ticket</h2><p>As novas solicitações dos clientes aparecerão aqui.</p></div>:<><div className="staffConversationHead"><button className="staffBack" onClick={()=>setSelected(null)}>←</button><div><small>#{selected.id.slice(0,8)}</small><h2>{selected.subject}</h2></div><select value={selected.status} onChange={e=>status(e.target.value)}><option value="open">Novo</option><option value="in_progress">Em atendimento</option><option value="resolved">Resolvido</option></select></div><div className="staffMessages">{messages.map(m=>{const mine=m.sender_id===user.id;return <div key={m.id} className={'staffBubble '+(mine?'staffMine':m.is_system?'staffSystem':'staffCustomer')}><div><b>{mine?(m.sender_name||profile.full_name||'Suporte'):m.is_system?'Nexium Assistente':'Cliente'}</b>{mine&&<em>{m.sender_role||'Suporte'}</em>}</div><p>{m.message}</p><small>{new Date(m.created_at).toLocaleString('pt-BR')}</small></div>})}</div><div className="staffReply"><textarea rows={2} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Responder ao cliente..." onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><button onClick={send} disabled={!reply.trim()}><Send/></button></div>{msg&&<span className="staffError">{msg}</span>}</>}</article></section></main>
}